export const clusterOrganizationLogos: Record<string, string> = {
  "АО «АМИРА»": "/member-logos/amira.svg",
  "АО «БСК»": "/member-logos/bsk.png",
  "АО «ДНИИМФ»": "/member-logos/dniimf.png",
  "АО «МРТС»": "/member-logos/mrts.svg",
  "АО «Протон»": "/member-logos/proton.svg",
  "АО «СЗ ЭМИ»": "/member-logos/szemi.svg",
  "НИППППД «НЕДРА»": "/member-logos/nedra.png",
  "НПО «ПТР»": "/member-logos/npo-ptr.png",
  "НПП «МЕТРОМАТИКА»": "/member-logos/metromatika.svg",
  "НПЦ «Родемос»": "/member-logos/rodemos.svg",
  "ООО «Айтуби»": "/member-logos/it2b.png",
  "ООО «Атоминопром»": "/member-logos/atominoprom.svg",
  "ООО «ВИДЖО»": "/member-logos/vidzho.svg",
  "ООО «Газстройпром»": "/member-logos/gazstroyprom.svg",
  "ООО «Газстройтех»": "/member-logos/gazstroytech.svg",
  "ООО «ЕВРАЗ Стил Билдинг»": "/member-logos/evraz-steel-building.svg",
  "ООО «ЕВРАЗ Стил Бокс»": "/member-logos/evraz-steel-box.png",
  "ООО «ЗВО Инновент»": "/member-logos/innovent.png",
  "ООО «Импэкс Электро»": "/member-logos/impex-electro.png",
  "ООО «ИСМ»": "/member-logos/ism.svg",
  "ООО «Каскад»": "/member-logos/kaskad.png",
  "ООО «Комплексный проект»": "/member-logos/complex-project.png",
  "ООО «Либерти Лайнс»": "/member-logos/liberty-lines.png",
  "ООО «ЛИТАНА»": "/member-logos/litana.png",
  "ООО «ЛИТЕКС»": "/member-logos/liteks.png",
  "ООО «МРС»": "/member-logos/mrs.svg",
  "ООО «ПК-Термоснаб»": "/member-logos/termoclip.svg",
  "ООО «Полипласт Новомосковск»": "/member-logos/polyplast-novomoskovsk.svg",
  "ООО «ППФ Технические системы»": "/member-logos/technical-systems.png",
  "ООО «РИК»": "/member-logos/rik.png",
  "ООО «Сибэнергомаш-БКЗ»": "/member-logos/sibem-bkz.svg",
  "ООО «Современные интеллектуальные системы»": "/member-logos/sis.png",
  "ООО «СпецБалтМебель»": "/member-logos/specbaltmebel.svg",
  "ООО «ССТ»": "/member-logos/sst.webp",
  "ООО «Табаган»": "/member-logos/tabagan.png",
  "ООО «ТЕРМОКЛИП»": "/member-logos/termoclip.svg",
  "ООО «ТЕХАТОМСТРОЙ»": "/member-logos/tehatomstroy.svg",
  "ООО «ТыЯплюс»": "/member-logos/youiplus.png",
  "ООО «УралНИИстром»": "/member-logos/uralniistrom.svg",
  "ООО «Фирма ОРГРЭС»": "/member-logos/orgres.svg",
  "ООО «Холдинг Кабельный Альянс»": "/member-logos/holdcable.png",
  "ООО «ЦРСТ»": "/member-logos/crst.png",
  "ООО «Энергопласт»": "/member-logos/energoplast.png",
  "ООО «Энергострой»": "/member-logos/energostroy.png",
  "ООО «ЭНСО-Инжиниринг»": "/member-logos/enso.svg",
  "СМТ": "/member-logos/smt.png",
  "ХК «Новолекс»": "/member-logos/novolex.svg",
  "ЦМС «Чайка»": "/member-logos/chaika.svg",
  "Щёлковский завод КМК": "/member-logos/kmk.svg",
};
